project: 
  type: website
  output-dir: docs
execute:
  freeze: auto  

website:
  open-graph: true
  page-navigation: true  
  title: "Marburg Open Forest"
  site-url: https://MarburgOpenForest.github.io/
  repo-url: https://github.com/MarburgOpenForest/MOFknowledge
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: textbox
  page-footer: "Faculty of Geography (2018-2023)" 
  # twitter-card:
  #   creator: "@yxz"
  # comments:
  #   utterances:
  #     repo: yourgithubname/yourreponame
  navbar:
    logo: /images/logo.jpg
    left:
      - icon: question-square-fill
        text: FAQ
        href: base/faq.qmd
      - icon: journals
        text: Self-study
        href: modules/slidelist.qmd             
    #   - icon: file-slides-fill
    #     text: Slides
    #     href: slides/slidelist.qmd
    #   - icon: check2-square
    # #     text: Test It
    #     href: assessment/slidelist.qmd   
    # # right:
    #   - icon: chat-left-text-fill
    #     text: Ilias
    #     href: https://ilias.uni-marburg.de/login.php?target=&client_id=UNIMR&cmd=force_login
    tools:
      - icon: github
        href: https://github.com/MarburgOpenForest/MOFknowledge
        text: "repo" 
  sidebar:
    # logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Welcome"
        contents:
          - index.md
          - base/about.qmd
      - text: "---"
      - section: "MOFgeoDB"
        contents:
          - mofgeodb/mof-geodb-about.qmd
          - mofgeodb/mof-geodb-views.qmd
          - mofgeodb/mof-geodb-plots.qmd
          - mofgeodb/mof-geodb-plots.qmd
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-fieldwork/
          #   text: uav/Flight Planning
      - text: "---"
      # - section: "topic2"
      #   contents:
      #     - topic2/topic2-index.qmd
          

#format: dokuwiki
format:
  html:
    theme:
      light: lumen
      dark: [lumen, css/theme-dark.scss]
    code-background: true
    code-copy: true
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
# filters:
#   - include-files.lua
#   - quarto