project: 
  type: website
  output-dir: docs
execute:
  freeze: auto  

website:
  open-graph: true
  page-navigation: true  
  title: "Marburg Open Forest"
  site-url: https://marburgopengorest.github.io
  repo-url: https://github.com/marburgopenforest/MOFknowledge
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: textbox
  page-footer: "Faculty of Geography - gisma spatial science ressources (2018-2024)" 
  comments:
    utterances:
      repo: MarburgOpenForest/MOFknowledge
  navbar:
    logo: /images/logo.jpg
    left:
    - icon: question-square-fill
      text: FAQ
      href: base/faq.qmd
  #  - icon: journals
  #    text: Self-study
  #    href: modules/slidelist.qmd
  #  - icon: file-slides-fill
  #    text: Slides
   #   href: slides/slidelist.qmd
    # - icon: check2-square
    #   text: Test It
    #   href: assessment/slidelist.qmd
    # right:
    # - icon: chat-left-text-fill
    #   text: Ilias
    #   href: https://ilias.uni-marburg.de/login.php?target=&client_id=UNIMR&cmd=force_login
    tools:
    - icon: github
      href: https://github.com/MarburgOpenForest/MOFknowledge
      text: "repo"
  sidebar:
    logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/MarburgOpenForest/MOFknowledge
        text: "repo" 
    contents:
      - section: "Welcome"
        contents:
          - index.md
        #  - base/about.qmd
      - text: "---"
      - section: "MOFgeoDB"
        contents:
          - mofgeodb/mof-geodb-about.qmd
          - mofgeodb/mof-geodb-views.qmd
          - mofgeodb/mof-geodb-plots.qmd
          - mofgeodb/mof-geodb-lookup.qmd
          - mofgeodb/mof-geodb-trigger.qmd
          - mofgeodb/mof-geodb-experiments.qmd
          - mofgeodb/mof-geodb-datacollect.qmd
          - mofgeodb/mof-geodb-analysis.qmd
          - mofgeodb/mof-geodb-lit.qmd
      - text: "---"          
          - href: http://137.248.191.201:8000/?PROJECT=creu/MOFGeoDB
            text: WebGIS MOFGeoDB
      - text: "---"
      - section: "WebGIS UAV Data"
        contents:
          - uav/mof-uav-about.qmd        
          - href: http://137.248.191.201:5000/r/uav
            text: "Webserver droneDB"   

   

#format: dokuwiki
format:

  html:
    theme:
      light: [flatly, css/nav.scss]
      dark: [darkly, css/theme-dark.scss]
    code-background: true
    code-copy: true
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
# filters:
#   - include-files.lua
#   - quarto
